### ISSUE TITLE
system level logging does not report utilisation information

### ISSUE THREAD

**Issue by wwonigkeit** [vorteil/vorteil#117]
### Problem description

When the following configuration is applied:

```toml
[[logging]]
  config = ["Name=tcp", "Host=35.201.9.144", "Port=3000", "Format=json"]
  type = "system"

[[logging]]
  config = ["Name=tcp", "Host=35.201.9.144", "Port=3000", "Format=json"]
  type = "kernel"
```

Kernel messages are received, however, the system messages with the CPU, memory, disk and network information is not received.

### Expected behaviour

Expect to see these types of messages

```json
[{"date":1570599209.000048,"cpu_p":13.000000,"user_p":12.000000,"system_p":1.000000,"cpu0.p_cpu":13.000000,"cpu0.p_user":12.000000,"cpu0.p_system":1.000000},{"date":1570599210.000038,"cpu_p":99.000000,"user_p":93.000000,"system_p":6.000000,"cpu0.p_cpu":99.000000,"cpu0.p_user":93.000000,"cpu0.p_system":6.000000},{"date":1570599211.000217,"cpu_p":89.000000,"user_p":87.000000,"system_p":2.000000,"cpu0.p_cpu":89.000000,"cpu0.p_user":87.000000,"cpu0.p_system":2.000000},{"date":1570599212.000099,"cpu_p":0.000000,"user_p":0.000000,"system_p":0.000000,"cpu0.p_cpu":0.000000,"cpu0.p_user":0.000000,"cpu0.p_system":0.000000},{"date":1570599213.000217,"cpu_p":0.000000,"user_p":0.000000,"system_p":0.000000,"cpu0.p_cpu":0.000000,"cpu0.p_user":0.000000,"cpu0......
```

### Actual behaviour

Only kernel messages are received.

### Steps to reproduce

Configure the vcfg file with:
```toml
[[logging]]
  config = ["Name=tcp", "Host=35.201.9.144", "Port=3000", "Format=json"]
  type = "system"

[[logging]]
  config = ["Name=tcp", "Host=35.201.9.144", "Port=3000", "Format=json"]
  type = "kernel"
```

### System details

Please include details about the system that the issue can be reproduced on, including:

Version: 0.5.6
Ref: 764564e
Released: Wed, 28 Oct 2020 01:00:09 +0000
Verified on AWS & GCP

**Comment by wwonigkeit** [comment]
Issue is with the latest version of FluentBit. The TCP stream is sent without a newline delimiter which causes the TCP logstash pipeline to buffer all of the performance information.

Changed the vcfg file to the following:

```toml
[[logging]]
  config = ["Name=http", "Host=35.201.9.144", "Port=3000", "Format=json"]
  type = "system"
```

and configured the logstash to accept HTTP messages in stead of TCP
