### ISSUE TITLE
Firecracker visualizer logic earlier than kernel manager logic

### ISSUE THREAD

**Issue by jalfvort** [vorteil/vorteil#45]
It looks like the Firecracker visualizer is running earlier than the kernel manager or whatever merges the default kernel values. Here is an example of what kind of problem this causes:
### Scenario 1 - Not Kernel defined :
**VCFG**
```toml
....
[vm]
  cpus = 1
  ram = "91 MiB"
  inodes = 100
  disk-size = "+10 MiB"
```

```sh
.$ /cli run /tmp/helloworld/ --platform firecracker
Scanning inputs  ⠋                                                                                
Writing image done [=================================] 32.0 MiB / 32.0 MiB
Kernel 'firecracker-' VMLinux does not exist
```
_visualizers logic thinks kernel is = "" , but it should be whatever the default / latest kernel is._

### Scenario 2 - Old Kernel defined :
**VCFG**
```toml
....
[vm]
  cpus = 1
  ram = "91 MiB"
  inodes = 100
  kernel = "20.8.3"
  disk-size = "+10 MiB"
```

```sh
$ ./cli run /tmp/helloworld/ --platform firecracker
Scanning inputs  ⠋                                                                                
Requested kernel '20.8.3' is too old for this compiler. Using latest kernel instead.
Writing image done [==============================] 32.0 MiB / 32.0 MiB
Kernel 'firecracker-20.8.3' VMLinux does not exist
```
_visualizers logic thinks kernel is = "20.8.3" (from vcfg) , but it should be whatever the default / latest kernel is (kernel manger is setting this)._
